Create service account # Optional

# Fetch Secret from serviceaccount
kubectl describe serviceAccounts "serviceaccount"

# Now, describe that token
kubectl describe screts "Tokens values"

# Get the certificate from exixting cluster
kubectl config view --flatten --minify

# Create Kubceonfig.yaml
## just change from my template

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {GET FROM COMMAND NO.10}

    server: {GET FROM COMMAN NO.10}
  name: {GET FROM COMMAN NO.10}

contexts:
- context:
    cluster: {GET FROM COMMAN NO.10}
    namespace: {USE kubectl get namespaces to choose}
    user: {GET FROM COMMAN NO.10}
  name: {GET FROM COMMAN NO.10} / U canspecifiy your username
current-context: {GET FROM COMMAN NO.10}
kind: Config
users:
- name: {GET FROM COMMAN NO.10} / U can specifiy your username
  user:
    token: {GET FROM COMMAN NO.7}



