apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    apps: nextcloud
spec:
  selector:
    app: nextcloud
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  labels:
    app: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: frontend
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:stable-apache
        ports:
        - containerPort: 80
          name: nextcloud
        volumeMounts:
        - name: nextcloud-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc
